services:

  ##################################################################################################################
  ########################################### Kafka Cluster ########################################################
  ##################################################################################################################

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.4.1'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: 'confluentinc/cp-kafka:7.4.1'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



  ##################################################################################################################
  ########################################### Data Bases ###########################################################
  ##################################################################################################################
  payment-db:
    image: 'postgres:16'
    container_name: 'payment-db'
    environment:
      - POSTGRES_USER=payment
      - POSTGRES_PASSWORD=payment
      - POSTGRES_DB=paymentdb
    ports:
      - '5433:5432'
    volumes:
      - './payment-service/init-payment.sql:/docker-entrypoint-initdb.d/init.sql'
    command: "postgres -c wal_level=logical"
